language: rust

rust:
  - stable
  - beta
  - nightly

install:
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo fmt --all -- --check
  - cargo clippy --all -- -D warnings
  - cargo test --all

