language: rust

rust:
  - stable
  - beta
  - nightly

install:
  - if [[ $TRAVIS_RUST_VERSION == "stable" ]]; then rustup component add rustfmt; fi
  - if [[ $TRAVIS_RUST_VERSION == "stable" ]]; then rustup component add clippy; fi

script:
  - if [[ $TRAVIS_RUST_VERSION == "stable" ]]; then cargo fmt --all -- --check; fi
  - if [[ $TRAVIS_RUST_VERSION == "stable" ]]; then cargo clippy --all -- -D warnings; fi
  - cargo test --all
